### PR TITLE
Support flatpath option

### PR DESCRIPTION
**Pull request by jacobbroberg**
`flatpath` will like `flat` result in a one layer deep json object, but where the path is included, separated with double underscores

### CODE REVIEW

**Comment by briangonzalez** [comment]
I'd prefer to have a customer delimiter option, so a user could pass in an arbitrary delimiter. Right now the default is `:`.

https://github.com/briangonzalez/gulp-file-contents-to-json/blob/master/index.js#L47

Thoughts?

**Comment by jacobbroberg** [comment]
I think a custom delimiter is a good idea, as long as the result is a flattened list with the path included in the id.
Any idea for the name of such an option, that both describe that this is a path delimiter and results in a flattened list? `flatpathdelimiter`?
I'll update the pull request.

**Comment by PrimeLens** [comment]
please keep the default as ':' if nothing is passed

**Comment by jacobbroberg** [comment]
Updated so that `flatpathdelimiter` gives a flattened list with a custom delimiter. If not set, result is that same as usual: a tree structure using the ':' delimiter (as @PrimeLens mentioned)

**Comment by briangonzalez** [comment]
@jacobbroberg Why not pass a generic option for all delimiters? 

```
delimiter: "__"
```

**Comment by jacobbroberg** [comment]
@briangonzalez  Fine for me to rename `flatpathdelimiter` to `delimiter`. 
But maybe I'm missing something, but the end result will not be different from now:
If I set the delimiter to anything other than ':' calling `JSON.stringify()` will result in a flat list (not flat in the sense that the path is stripped away as the `flat` option does, but in the sense that the resulting JSON is only one level deep, as opposed to using the ':' delimiter which will result in a folder structure like tree hierarchy).
If I were to set the `flat` option to true, the `delimiter` option would not make any difference anyway.

So my question is: is it just a matter of renaming to the more simple option name `delimiter`, which implicitly will give a flat list - or am I missing something here?

**Comment by jacobbroberg** [comment]
@briangonzalez is renaming `flatpathdelimiter` to `delimter` enough for you or do you wish me to make further changes before this can be merged in?

**Comment by briangonzalez** [comment]
@jacobbroberg 

I guess I am still a little unclear about what this feature does. I want the API and config to remain really simple and dumb. 

Can you break down what the difference in the output is when this is enabled?

**Comment by jacobbroberg** [comment]
@briangonzalez  I totally support your goal in having a dumb and simple API.

### Example:

**Input:**

```
foo/file1.html
foo/bar/file2.html
foo/bar/baz/file3.html
qux/file4.html
```

**Normal output:**
using only default options

``` json
{
  "foo": {
    "file1.html": "<file1_contents>",
    "bar": {
      "file2.html": "<file2_contents>",
      "baz": {
        "file3.html": "<file3_contents>"
      }
    }
  },
  "qux": {
    "file4.html": "<file4_contents>"
  }
}
```

**Flat output:**
with `flat : true` option set

``` json
{
  "file1.html": "<file1_contents>",
  "file2.html": "<file2_contents>",
  "file3.html": "<file3_contents>",
  "file4.html": "<file4_contents>"
}
```

**Delimiter output:**
with `delimiter: '__'` (or currently `flatpathdelimiter: '__'`) option set resulting in "_flattened output, but where the path is included, separated with the custom delimiter_"

``` json
{
  "foo__file1.html": "<file1_contents>",
  "foo__bar__file2.html": "<file2_contents>",
  "foo__bar__baz__file3.html": "<file3_contents>",
  "qux__file4.html": "<file4_contents>"
}
```

I hope this illustrates what I am trying to achieve: at flattened output while preserving the path information from the input in the json key naming. By the way, this is this is the default output of the fork [gulp-file-contents-to-modules](https://github.com/yaireo/gulp-file-contents-to-modules) which I originally tried using, but I prefer the json output.

**Comment by briangonzalez** [comment]
Ahhh, this is super helpful and exactly what I needed. Thanks!

So here's the config I see:

``` js
delimiter: '__'
flat: true,
includeDirs: true // default false 
```

**Comment by jacobbroberg** [comment]
@briangonzalez  
I have updated according to your suggested options.

However, just for the record I would like to mention that we have more options that possible outcomes:

Setting `delimiter` will always cause a "flattened" output, since a json multi layered hierarchy is only constructed if `delimiter: ':'` (likewise if `delimiter: ':'` then it and `includeDirs` have no effect).

Options:

```
delimiter: '<something>'
flat: true
includeDirs: true
```

and 

```
delimiter: '<something>'
flat: false
includeDirs: false
```

and

```
delimiter: '<something>'
```

all give the same result.

Likewise, if `flat: true` and `includeDirs: false`, the `delimiter` option has no effect whatsoever.

I'm fine with this and these options are certainly more readable than my previous suggestions, but still: more options that possible outcomes.

**Comment by briangonzalez** [comment]
Ah, I get you. Sorry, I was brain-farting over here.

Maybe your first option is the best then?

**Comment by jacobbroberg** [comment]
Okay, so do you want to keep it like this or should I revert the last commit?

**Comment by briangonzalez** [comment]
Let's go ahead and go back to the original solution. I owe you a beer.

**Comment by jacobbroberg** [comment]
Last commit reverted - emoji beer will do :beer:  :smile:

**Comment by briangonzalez** [comment]
:beer:

**Comment by jacobbroberg** [comment]
@briangonzalez Do you plan to to add a new release to npm with this in the recent future? Otherwise I will keep using my own fork.

**Comment by briangonzalez** [comment]
Done! v0.2.0 just published.

**Comment by jacobbroberg** [comment]
:+1:

**Pull request merged**
